# Generated by Django 5.1.2 on 2024-10-29 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='rol',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Desarrollador', 'Desarrollador'), ('Recursos Humanos', 'Recursos Humanos'), ('Vendedor', 'Vendedor')], max_length=50),
        ),
    ]
